package com.demo.myspringboot.entity;

import com.baomidou.mybatisplus.annotation.TableLogic;
import com.baomidou.mybatisplus.annotation.Version;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

/**
 * @version 1.0
 * @className CommonEntity
 * @Author xiaolu
 * @date 2021/2/5 9:54
 */
@Data
public class CommonEntity implements Serializable {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employee
     *
     * @mbg.generated Thu Feb 04 18:44:07 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     *
     * @mbg.generated Thu Feb 04 18:44:07 CST 2021
     */
    @Version
    private Integer version;

    /**
     *
     * 是否删除（0：否；1：是）
     * @mbg.generated Thu Feb 04 18:44:07 CST 2021
     */
    @TableLogic
    private String isDeleted;

    /**
     *
     *
     * @mbg.generated Thu Feb 04 18:44:07 CST 2021
     */
    private String createdBy;

    /**
     *
     *
     * @mbg.generated Thu Feb 04 18:44:07 CST 2021
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") // 转化前端时间为Date
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone = "GMT+8") // 后端Date转化客串给前端
    private Date createdDate;

    /**
     *
     *
     * @mbg.generated Thu Feb 04 18:44:07 CST 2021
     */
    private String updatedBy;

    /**
     *
     *
     * @mbg.generated Thu Feb 04 18:44:07 CST 2021
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") // 转化前端时间为Date
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss",timezone = "GMT+8") // 后端Date转化客串给前端
    private Date updatedDate;

}